### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by cadillacben** [JPipkin/SFDC-Record-Type-Picklist#7]
Thank you for creating this.  I am trying to get it going in my sandbox, but I seem to have an auth issue somewhere.  

I feel like I followed the instructions correctly and the named credential shows as authenticated as me.  When trying it though I get an error 403 in my debug log.

**Comment by RussMissionPros** [comment]
Hope you've solved this by now! For me the issue was in step 1.vi I forgot to select the second value, "Perform requests on your behalf at any time (refresh_token, offline_access)"

**Comment by cadillacben** [comment]
I honestly can't remember exactly what solved it for me, but I bet that was it.  I just failed to update this.  :(
